"""MCP proxy adapter — registers ``target_system: "mcp"`` in the Statis worker.

This adapter handles ``mcp_tool_call`` actions generated by the Statis MCP
middleware or any caller that sets ``target_system="mcp"`` on a proposal.

It enables MCP-native agents (Claude, Cursor, Cline, etc.) to POST tool calls
directly to the Statis API without using the Python SDK — the adapter receives
the approved action and either logs it (default) or forwards it to a configured
MCP server.

Configuration
-------------
To forward calls to a real MCP server, set ``mcp_server_url`` in the worker
adapter configuration (``worker/adapters.yaml``):

    adapters:
      mcp:
        class: MCPProxyAdapter
        config:
          mcp_server_url: "http://localhost:3333"

If ``mcp_server_url`` is not configured the adapter logs the call and returns
a success result — identical to the ``GenericAdapter`` pattern. This makes
``target_system: "mcp"`` safe to use without a running MCP server, which is
the correct default for shadow-mode evaluation and receipt generation.
"""
from __future__ import annotations

import json
import logging
import os
from typing import Any, Optional
from urllib.request import Request, urlopen
import urllib.error

from .base import BaseAdapter, ExecutionResult

logger = logging.getLogger(__name__)


class MCPProxyAdapter(BaseAdapter):
    """Execute approved MCP tool calls via the Statis worker.

    Supported action type:
      - ``mcp_tool_call`` — generic MCP tool invocation

    Expected ``parameters`` keys:
      - ``tool_name`` (str, required) — the MCP tool to call
      - ``tool_input`` (dict, optional) — arguments forwarded to the tool

    Configuration:
      mcp_server_url — base URL of the upstream MCP server to forward the
                       call to. If not set, the adapter logs and succeeds
                       (GenericAdapter behaviour). This is the correct
                       default for shadow mode.
    """

    SUPPORTED_ACTION_TYPES = {"mcp_tool_call"}

    def __init__(self, mcp_server_url: Optional[str] = None) -> None:
        # Accept the URL from constructor arg or environment variable.
        # Deliberately does NOT raise if missing — GenericAdapter pattern.
        self._mcp_server_url: str = (
            mcp_server_url
            or os.environ.get("MCP_SERVER_URL", "")
        ).rstrip("/")

    # ------------------------------------------------------------------
    # BaseAdapter
    # ------------------------------------------------------------------

    def execute(self, action: Any) -> ExecutionResult:
        action_id: str = (
            action.action_id if hasattr(action, "action_id") else action["action_id"]
        )
        action_type: str = (
            action.action_type if hasattr(action, "action_type") else action["action_type"]
        )
        parameters: dict = (
            action.parameters
            if hasattr(action, "parameters")
            else action.get("parameters", {})
        )

        if action_type not in self.SUPPORTED_ACTION_TYPES:
            return ExecutionResult(
                success=False,
                result={},
                error=(
                    f"MCPProxyAdapter does not handle action_type={action_type!r}. "
                    f"Supported: {sorted(self.SUPPORTED_ACTION_TYPES)}"
                ),
            )

        tool_name: str = parameters.get("tool_name", "")
        tool_input: dict = parameters.get("tool_input") or {}

        if not tool_name:
            return ExecutionResult(
                success=False,
                result={},
                error="parameters.tool_name is required for mcp_tool_call",
            )

        # ------------------------------------------------------------------
        # Forward to MCP server if configured; otherwise log only.
        # ------------------------------------------------------------------

        if self._mcp_server_url:
            return self._forward_to_mcp_server(
                action_id=action_id,
                tool_name=tool_name,
                tool_input=tool_input,
            )

        # GenericAdapter pattern: log and return success.
        logger.info(
            "mcp_tool_call logged (no mcp_server_url configured) "
            "action_id=%s tool_name=%s",
            action_id,
            tool_name,
        )
        return ExecutionResult(
            success=True,
            result={
                "action_id": action_id,
                "tool_name": tool_name,
                "tool_input": tool_input,
                "forwarded": False,
                "note": (
                    "Configure mcp_server_url in adapter config to forward "
                    "to a real MCP server."
                ),
            },
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _forward_to_mcp_server(
        self,
        action_id: str,
        tool_name: str,
        tool_input: dict,
    ) -> ExecutionResult:
        """POST an MCP JSON-RPC tool-call request to the configured server."""
        payload = {
            "jsonrpc": "2.0",
            "id": action_id,
            "method": "tools/call",
            "params": {
                "name": tool_name,
                "arguments": tool_input,
            },
        }

        try:
            data = json.dumps(payload).encode()
            req = Request(
                f"{self._mcp_server_url}/",
                data=data,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urlopen(req, timeout=30) as resp:
                body = json.loads(resp.read())

            logger.info(
                "mcp_tool_call forwarded action_id=%s tool_name=%s",
                action_id,
                tool_name,
            )
            return ExecutionResult(
                success=True,
                result={
                    "action_id": action_id,
                    "tool_name": tool_name,
                    "forwarded": True,
                    "mcp_response": body,
                },
            )

        except urllib.error.HTTPError as exc:
            body_text = exc.read().decode() if exc.fp else ""
            return ExecutionResult(
                success=False,
                result={},
                error=f"MCP server returned HTTP {exc.code}: {body_text}",
            )
        except Exception as exc:
            return ExecutionResult(
                success=False,
                result={},
                error=f"MCP server request failed: {exc}",
            )
