"""statis init adapter — scaffold a new Statis adapter from template.

Usage:
    statis init adapter --name=MyAdapter --action-types=create_record,update_record
"""
from __future__ import annotations

import os
import re
import sys


# ---------------------------------------------------------------------------
# Name normalization
# ---------------------------------------------------------------------------

def _to_snake_case(name: str) -> str:
    """Convert any adapter name to snake_case filename."""
    # Remove 'Adapter' suffix if present
    name = re.sub(r"Adapter$", "", name, flags=re.IGNORECASE).strip()
    # Replace spaces/hyphens with underscores
    name = re.sub(r"[\s\-]+", "_", name)
    # CamelCase → snake_case
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    name = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", name)
    return name.lower().strip("_")


def _to_class_name(name: str) -> str:
    """Convert any adapter name to a PascalCase class name ending in Adapter."""
    snake = _to_snake_case(name)
    parts = snake.split("_")
    pascal = "".join(p.capitalize() for p in parts if p)
    if not pascal.endswith("Adapter"):
        pascal += "Adapter"
    return pascal


def _parse_action_types(raw: str) -> list[str]:
    return [t.strip() for t in raw.split(",") if t.strip()]


# ---------------------------------------------------------------------------
# File generation
# ---------------------------------------------------------------------------

def _adapter_stub(class_name: str, action_types: list[str]) -> str:
    methods = ""
    for at in action_types:
        methods += f"""
    def _{at}(self, action) -> dict:
        # TODO: implement {at}
        # Call the external API here and return a result dict.
        raise NotImplementedError("{at} not yet implemented")
"""

    dispatch = "\n".join(
        f'        if action.action_type == "{at}":\n            return self._{at}(action)'
        for at in action_types
    )

    return f'''"""Auto-generated by `statis init adapter`. Fill in the TODOs."""
from __future__ import annotations

from app.adapters.base import BaseAdapter, ExecutionResult


class {class_name}(BaseAdapter):
    """Statis adapter for [describe target system here].

    Action types:
{chr(10).join(f"        - {at}" for at in action_types) if action_types else "        - (none specified)"}
    """

    def __init__(self, **config):
        # TODO: accept credentials/config (API key, base URL, etc.)
        pass

    def execute(self, action) -> ExecutionResult:
        """Dispatch to the appropriate action type handler."""
        try:
{dispatch if dispatch else "            pass  # no action types specified"}
            return ExecutionResult(success=False, result={{}}, error=f"Unknown action_type: {{action.action_type!r}}")
        except Exception as exc:
            return ExecutionResult(success=False, result={{}}, error=str(exc))
{methods}'''


def _test_stub(class_name: str, snake_name: str, action_types: list[str]) -> str:
    test_cases = "\n\n".join(
        f'''@pytest.mark.skip(reason="not yet implemented")
def test_{at}(adapter):
    action = MagicMock()
    action.action_type = "{at}"
    action.parameters = {{}}
    result = adapter.execute(action)
    assert result.success'''
        for at in action_types
    ) or f"""@pytest.mark.skip(reason="no action types specified")
def test_placeholder(adapter):
    pass"""

    return f'''"""Tests for {class_name}. Generated by `statis init adapter`."""
import pytest
from unittest.mock import MagicMock

from adapters.{snake_name} import {class_name}


@pytest.fixture
def adapter():
    return {class_name}()


{test_cases}
'''


def _readme_row(snake_name: str, class_name: str, action_types: list[str]) -> str:
    types_str = ", ".join(f"`{t}`" for t in action_types) if action_types else "—"
    return f"| `{snake_name}` | `{class_name}` | {types_str} |\n"


# ---------------------------------------------------------------------------
# Main entrypoint
# ---------------------------------------------------------------------------

def run_init_adapter(name: str, action_types_raw: str = "", sdk_root: str | None = None) -> int:
    if not name or not name.strip():
        print("Error: --name is required and cannot be empty.", file=sys.stderr)
        return 1

    if sdk_root is None:
        # Infer from this file's location: sdk_root = statis-sdk/
        sdk_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(
            os.path.abspath(__file__)
        ))))

    snake = _to_snake_case(name)
    class_name = _to_class_name(name)
    action_types = _parse_action_types(action_types_raw)

    adapter_path = os.path.join(sdk_root, "adapters", f"{snake}.py")
    test_path = os.path.join(sdk_root, "python", "tests", f"test_{snake}.py")
    readme_path = os.path.join(sdk_root, "adapters", "README.md")

    # Duplicate detection
    if os.path.exists(adapter_path):
        print(f"Error: {adapter_path} already exists. Remove it first.", file=sys.stderr)
        return 1
    if os.path.exists(test_path):
        print(f"Error: {test_path} already exists. Remove it first.", file=sys.stderr)
        return 1

    # Write adapter stub
    os.makedirs(os.path.dirname(adapter_path), exist_ok=True)
    with open(adapter_path, "w") as f:
        f.write(_adapter_stub(class_name, action_types))
    print(f"Created: {adapter_path}")

    # Write test stub
    os.makedirs(os.path.dirname(test_path), exist_ok=True)
    with open(test_path, "w") as f:
        f.write(_test_stub(class_name, snake, action_types))
    print(f"Created: {test_path}")

    # Append README row
    row = _readme_row(snake, class_name, action_types)
    if os.path.exists(readme_path):
        with open(readme_path, "a") as f:
            f.write(row)
        print(f"Updated: {readme_path}")
    else:
        print(f"Note: {readme_path} not found — skipping README update.")

    print(f"\nAdapter '{class_name}' scaffolded. Next steps:")
    print(f"  1. Fill in credentials/config in {class_name}.__init__")
    print(f"  2. Implement each action type handler")
    print(f"  3. Run tests: pytest {test_path}")

    return 0
